### ISSUE TITLE
[Feature request] Add suggested peers list

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#1187] opened 2023-04-24 08:12 UTC
### Description
We've seen many new Blixt users that don't know with which other nodes that could open channels in Blixt.
Or [situations like this one](https://stacker.news/items/168526), when the new user don't even know that you  can open channels in Blixt with whatever other node.
Many of them even open multiple Dunder channels, that are going only towards Blixt Node. And that is not efficient and good.
We need an option in Blixt that could suggest to the user a list of "vouched" node peers to open channels. Even a list of optional Dunder servers (we should encourage other nodes to run Dunder server for Blixt users).

### Solution proposal
In the main screen when the wallet is new, show suggestions, links or popup messages with nodes that user can select to open channels.
A good start can be used from the Blixt community peers from #1033 where Blixt community can vouch them and add more.

**Comment by Darth-Coin** [comment] 2023-06-06 13:49
Are many new users coming to Blixt but they don't know well how to open some LN channels but also with WHO, which peer is the best for Blixt to start.

So I saw how Bluewallet LDK resolve this: they added a simple scrolling lef-right with some good nodes, so user can choose and not even have to look for them.
![image](https://github.com/hsjoberg/blixt-wallet/assets/56997124/c69e83f9-de60-4ba6-b913-3b876101a274)

Can we offer something similar based on our community list of vouched peers for Blixt #1033  ?

**Comment by hsjoberg** [comment] 2023-06-30 12:06
Closing because of duplicate of #1137.

I'm not a fan of BlueWallet's GUI.
I think we should do a normal list instead, there we can maybe add scoring (stars) and other useful information for each node.

**Closed by hsjoberg** 2023-06-30 12:06 UTC
